[default]
# weak  → allows git URL installs, pip installs, and all manager features
# other options: strong | normal | weak | disable
security_level = weak
network_mode = personal_cloud

allow_git_url_install = true
allow_pip_install = true

git_exe = git
use_uv = false

file_logging = true

always_lazy_install = false

model_download_by_agent = true

default_cache_as_channel_url = false
bypass_ssl = false
